# 본래는 공개되면 안되는 정보. 공부한 것을 저장하기 위해 gitignore에서 제외함
jwt:
  key:
    access: O2O_Automatic_Store_System_Demo_AccessKey
    refresh: O2O_Automatic_Store_System_Demo_RefreshKey
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7