spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        use_sql_comments: true      # SQL 생성시 주석 포함
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: create
    open-in-view: true
    show-sql: true