spring:
  config:
    import:
      - security/application-token.yml
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: create
        default_batch_fetch_size: 100
    open-in-view: true
    show-sql: true
upload:
  image:
    location: images/