# 본래는 공개되면 안되는 정보. 공부한 것을 저장하기 위해 gitignore에서 제외함
jwt:
  key:
    access: TzJPX0F1dG9tYXRpY19TdG9yZV9TeXN0ZW1fMjM1X2FjY2Vzcw==
    refresh: TzJPX0F1dG9tYXRpY19TdG9yZV9TeXN0ZW1fMjM1X3JlZnJlc2g=
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7