spring:
  profiles:
    active: local
    include: secret
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true            # SQL 보기 좋게 출력
        highlight_sql: true         # SQL 색깔
        hbm2ddl.auto: create
    open-in-view: true
    show-sql: true
  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true